apiVersion: v1
kind: Service
metadata:
  name: caller-service
  labels:
    app: caller-service
spec:
  type: NodePort
  ports:
  - port: 8090
    name: http
  selector:
    app: caller-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: caller-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: caller-service
        version: v1
    spec:
      containers:
      - name: caller-service
        image: piomin/caller-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090