apiVersion: v1
kind: Service
metadata:
  name: callme-service
  labels:
    app: callme-service
spec:
  type: NodePort
  ports:
  - port: 8091
    name: http
  selector:
    app: callme-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: callme-service-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: callme-service
        version: v2
    spec:
      containers:
      - name: callme-service
        image: piomin/callme-service:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8091